# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Diary' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Diary
    pod 'RxSwift', '~> 4.0'
    pod 'RxCocoa', '~> 4.0'
    pod 'RealmSwift'
    pod 'RAMAnimatedTabBarController'
    pod 'JBDatePicker'
    pod 'Alamofire', '4.2'
    pod 'SWXMLHash', '~> 4.0.0'


  target 'DiaryTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DiaryUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
